### ISSUE TITLE
data augmentation

### ISSUE THREAD

**Issue by xwjBupt** [Artur112/Brats2019#4]
Hi Artur112! Thanks for sharing the code,but i am comfused with some code,in DataAugment.elastic_deform,if my Y is the same shape like the x(B,4,H,W,D),3 foreground + 1 background,each channel represents a class, what should i change in the code to adapt my Y? here is what i have changed ,is these right?

`    def elastic_deform(self, X, Y):
        # Elastic deformation with a random square deformation grid, where the displacements are sampled from a normal distribution with
        # standard deviation sigma. Applies elastic deformation in all 3 axes, if you wish to speed up training time change the d variable
        # to two axes chosen randomly. Uses elasticdeform package from gvtulder/elasticdeform.

        # the shape of X and Y are both (4,128,128,128)
        X = X.numpy()
        Y = Y.unsqueeze(1).numpy()
        brain_region = (X > 0).astype(
            'float') * 10  # Multiplying by 10 so there would be a bigger difference between foreground and background pixels to avoid voxels
        # being assigned the wrong label after the elastic deformation

        # Split the labels and deform them separately, as if done together together they'll get mixed up. 10 times multiplication again.
        lbl0 = Y[0] * 10.0  # the background
        lbl1 = Y[1] * 10.0
        lbl2 = Y[2] * 10.0
        lbl3 = Y[3] * 10.0
        sigma_nr = 5  # Random factor by which to deform
        # d = (1,2,3) # Axes in which to deform
        d = tuple(sorted(random.sample([1, 2, 3],
                                       k=2)))  # Use this instead if you wish to speed up training. Performs elastic transform over 2 axes only

        [X, brain_region, lbl0, lbl1, lbl2, lbl3] = elasticdeform.deform_random_grid(
            [X, brain_region, lbl0, lbl1, lbl2, lbl3],
            axis=[d] * 6, sigma=sigma_nr, points=3)

        brain_region = brain_region.astype('int') > 0
        X = X * brain_region  # To make sure background pixels remain 0 in the scans
        X[X < 0] = 0  # Remove any negative values - background values close 0

        lbl0[lbl1 < 0] = -1
        lbl1[lbl1 < 3] = -1
        lbl2[lbl2 < 3] = -1
        lbl3[lbl3 < 3] = -1

        Y = np.concatenate([lbl0, lbl1, lbl2, lbl3], axis=0).astype("float32")
        X = torch.from_numpy(X)
        Y = torch.from_numpy(Y)

        return X, Y`

thaks for your help!!

**Comment by Artur112** [comment]
Hi,
It seems correct. The only thing I might be worried about is that you're doing the elastic deformation on each label separately and concatenating them (as theyre one hot encoded), then you might get voxels that have two labels assigned to them. Doing it how it was before avoids this issue as it performs an argmax, any voxel gets a label based on which label has the highest value after the deformation. Please note this code is old and might have many issues. I have better code coming soon.

**Comment by xwjBupt** [comment]
ok,i understand ,thanks for your reply and looking forward to see your new code!!
thanks again !!
